user:
  jay:
    username : william
    password : 1234abcd!
  chen:
    username : 周杰伦
    password : 1234abcd!

url : http://www.tcpjwtester.top
#url : http://127.0.0.1:8000

mysql:
  db: trading_system
  host: localhost
  password: root
  port: 3306
  user: root